export const GET_HOMEPAGE_DATA_REQUEST = "GET_HOMEPAGE_DATA_REQUEST";
export const GET_HOMEPAGE_DATA_SUCCESS = "GET_HOMEPAGE_DATA_SUCCESS";
export const GET_HOMEPAGE_DATA_ERROR = "GET_HOMEPAGE_DATA_REQUEST";

//signup
export const GET_SIGNUP_REQUEST = "GET_SIGNUP_REQUEST";
export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";
export const GET_SIGNUP_ERROR = "GET_SIGNUP_ERROR";

//search
export const GET_SEARCH_COLLEGE_REQUEST = "GET_SEARCH_COLLEGE_REQUEST";
export const GET_SEARCH_COLLEGE_ERROR = "GET_SEARCH_COLLEGE_ERROR";
export const GET_SEARCH_COLLEGE_SUCCESS = "GET_SEARCH_COLLEGE_SUCCESS";

//news
export const GET_NEWS_REQUEST = "GET_NEWS_REQUEST";
export const GET_NEWS_ERROR = "GET_NEWS_ERROR";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";

//filters value
export const ADD_FILTERS = "ADD_FILTERS";
export const REMOVE_FILTERS = "REMOVE_FILTERS";

//all states
export const GET_STATES_REQUEST = "GET_STATES_REQUEST";
export const GET_STATES_SUCCESS = "GET_STATES_SUCCESS";
export const GET_STATES_ERROR = "GET_STATES_ERROR";

