export const GET_HOMEPAGE_DATA_REQUEST = "GET_HOMEPAGE_DATA_REQUEST"
export const GET_HOMEPAGE_DATA_SUCCESS = "GET_HOMEPAGE_DATA_SUCCESS"
export const GET_HOMEPAGE_DATA_ERROR = "GET_HOMEPAGE_DATA_REQUEST"