export const GET_HOMEPAGE_DATA_REQUEST = "GET_HOMEPAGE_DATA_REQUEST"
export const GET_HOMEPAGE_DATA_SUCCESS = "GET_HOMEPAGE_DATA_SUCCESS"
export const GET_HOMEPAGE_DATA_ERROR = "GET_HOMEPAGE_DATA_REQUEST"

//signup 
export const GET_SIGNUP_REQUEST = "GET_SIGNUP_REQUEST"
export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS"
export const GET_SIGNUP_ERROR = "GET_SIGNUP_ERROR"

//search
export  const GET_COLLEGE_REQUEST = "GET_COLLEGE_REQUEST"
export  const GET_COLLEGE_ERROR = "GET_COLLEGE_ERROR"
export  const GET_COLLEGE_SUCCESS = "GET_COLLEGE_SUCCESS"

//news 
export  const GET_NEWS_REQUEST = "GET_NEWS_REQUEST"
export  const GET_NEWS_ERROR = "GET_NEWS_ERROR"
export  const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS"

